# Generated by Django 3.2.7 on 2022-08-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateTimeField(),
        ),
    ]
